version: "2.0"

services:
  node:
    image: ghcr.io/akash-network/cosmos-omnibus:v0.4.23-jackal-v4.0.2
    env:
      - MONIKER=euro
      - CHAIN_ID=jackal-1
      - GENESIS_URL=https://snapshots.polkachu.com/genesis/jackal/genesis.json
      - P2P_SEEDS=ec38fb158ffb0272c4b7c951fc790a8f9849e280@198.244.212.27:26656,ade4d8bc8cbe014af6ebdf3cb7b1e9ad36f412c0@seeds.polkachu.com:17556
      - MINIMUM_GAS_PRICES=0.002ujkl
      - P2P_POLKACHU=1
      - STATESYNC_POLKACHU=1
      - CANINED_PRIV_VALIDATOR_LADDR=0.0.0.0:3333
      - CANINED_P2P_EXTERNAL_ADDRESS="<your assigned URI and forwarded port goes here>"
    expose:
      - port: 26657
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 3333
        to:
          - global: true
    params:
      storage:
        data:

          mount: /root/.canine

profiles:
  compute:
    node:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          - size: 500Mi
          - name: data
            size: 400Gi
            attributes:
              persistent: true
              class: beta3
  placement:
    dcloud:
      attributes:
        host: akash
#      signedBy:
#        anyOf:
#          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        node:
          denom: uakt
          amount: 10000

deployment:
  node:
    dcloud:
      profile: node
      count: 1
